services:
  hotel-app-bookings:
    build: ./booking-service
    deploy:
      replicas: 1
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/hotel-app
    depends_on:
      - mongodb

  hotel-app-users:
    build: ./user-service
    deploy:
      replicas: 1
    environment:
      - SEARCH_URI=http://hotel-app-search:8080
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/hotel-app
    depends_on:
      - mongodb

  hotel-app-search:
    build: ./search-service
    deploy:
      replicas: 1
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/hotel-app
    depends_on:
      - mongodb


  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - mongo-data:/data/db

  nginx:
    image: nginx:alpine
    container_name: nginx-server
    ports:
      - "3000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - hotel-app-users
      - hotel-app-bookings

volumes:
  mongo-data:
