services:
  hotel-app-bookings:
    build: ./booking-service
    deploy:
      replicas: 1
    environment:
      - SEARCH_URI=${SEARCH_URI}
      - SPRING_DATA_MONGODB_URI=${MONGODB_URI}
      - SPRING_DATA_REDIS_URI=${REDIS_URI}
      - JWT_SECRET=${JWT_SECRET}
      - RECEIPT_QUEUE=${REDIS_RECEIPT_QUEUE}

    depends_on:
      - mongodb
      - redis

  hotel-app-users:
    build: ./user-service
    deploy:
      replicas: 1
    environment:
      - SPRING_DATA_MONGODB_URI=${MONGODB_URI}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - mongodb

  hotel-app-search:
    build: ./search-service
    deploy:
      replicas: 1
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - REDIS_URI=${REDIS_URI}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - mongodb
      - redis

  hotel-app-worker:
    build: ./worker-service
    deploy:
      replicas: 1
    environment:
      - BOOKING_URI=${BOOKING_URI}
      - REDIS_URI=${REDIS_URI}
      - RECEIPT_QUEUE=${REDIS_RECEIPT_QUEUE}

    volumes:
      - recipts:/data/recipts

    depends_on:
      - redis

  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:latest
    container_name: redis

  nginx:
    image: nginx:alpine
    container_name: nginx-server
    ports:
      - "3000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - hotel-app-users
      - hotel-app-search
      - hotel-app-bookings
      - hotel-app-worker

volumes:
  mongo-data:
  recipts:
