spring.application.name=hotel-app
spring.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/hotel-db}
jwt.secret=asfjkkjcnakjsdhfnkajsdnfiewnfkasnaksjdfnvkasndckalsdfj
jwt.expiration= 3600000
server.port=8000

security.jwt.secret-key= 9a4f2c8oiuytrewd3ghye1f2a3b4c5d6e7f8a9b0c1d
security.jwt.expiration-time: 3600000