spring.application.name=hotel-app
spring.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/hotel-db}
server.port=8000
security.uri.search-uri=${SEARCH_URI:http://localhost:8080}

security.jwt.secret-key= ${JWT_SECRET:9aaskdljflaksjdflkajsdlfkjasclanslasdflk}
security.jwt.expiration-time= 3600000