spring.application.name=hotel-app
server.port=8000

spring.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/hotel-db}
security.uri.redis-uri=${SPRING_DATA_REDIS_URI:redis://localhost:6379}

security.uri.search-uri=${SEARCH_URI:http://localhost:8080}

security.key.booking-queue=${RECEIPT_QUEUE:RECEIPT_QUEUE}

security.jwt.secret-key= ${JWT_SECRET:9aaskdljflak  1   sjdflkajsdlfkjasclanslasdflk}
security.jwt.expiration-time= 3600000